name: DEV Package Pipeline

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  package-operations:
    uses: ./.github/workflows/package-operations.yml

    with:
      environment: dev
      package_name: maximo-demo-package
      dry_run: true
